allowCheckoutWithoutPayment: 0
allowEmptyCartOnCheckout: 0
allowPartialPaymentOnCheckout: 0
autoSetCartShippingMethodOption: 0
autoSetNewCartAddresses: 0
autoSetPaymentSource: 0
currency: EUR
freeOrderPaymentStrategy: complete
handle: primaryStore
minimumTotalPriceStrategy: default
name: 'Primary Store'
orderReferenceFormat: '{{number[:7]}}'
primary: 1
requireBillingAddressAtCheckout: 0
requireShippingAddressAtCheckout: 0
requireShippingMethodSelectionAtCheckout: 0
useBillingAddressForTax: 0
validateOrganizationTaxIdAsVatId: 0
