descriptionFormat: ''
handle: clothing
hasDimensions: false
hasProductTitleField: true
hasVariantTitleField: true
maxVariants: null
name: Kleidung
productFieldLayouts:
  d78b54ce-ee32-424d-9e6c-f0ed968dad9c:
    cardThumbAlignment: end
    cardView:
      - defaultSku
      - defaultPrice
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\commerce\fieldlayoutelements\ProductTitleField
            uid: e3765738-5bcd-4dbe-81d7-21964e433f5a
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            fieldUid: f85c7165-6da7-44a9-928c-57095d6f6cfe # Single: Rich Text
            handle: shopDescription
            includeInCards: false
            instructions: null
            label: 'Shop: Description'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9685f76e-56b9-401b-9caf-7874a62de5d5
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            fieldUid: fa611eaf-68fc-4c30-ba40-cf5bc4d0bcc0 # Shop: Facts
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2816d492-b811-4426-b4b1-dcea71ea1c2c
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            fieldUid: 52e7cb9c-4308-40be-a6ed-288b87ea2d9f # Shop: Product Images
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 878f4770-9e88-436b-aed4-dc39f580551b
            userCondition: null
            warning: null
            width: 100
        name: Info
        uid: 0f58e86c-d134-4430-bae0-74f899a71853
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            fieldUid: 85289f84-343d-4142-b42a-e68c64d7f7b9 # Promotion Categories
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 77687d47-6f52-4b21-af00-80d34af9b396
            userCondition: null
            warning: null
            width: 100
        name: Promotions
        uid: f9cc89f4-e40a-4e48-8c37-7b65c81f1f48
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            attribute: variants
            dateAdded: null
            elementCondition: null
            id: null
            includeInCards: false
            instructions: null
            label: null
            mandatory: true
            orientation: null
            providesThumbs: false
            requirable: false
            required: false
            tip: null
            translatable: false
            type: craft\commerce\fieldlayoutelements\VariantsField
            uid: cb6ab3a5-8647-4c3a-847a-aeebf5a95ab5
            userCondition: null
            warning: null
        name: Variants
        uid: f316006c-09f4-4655-b57e-de758ec380d2
        userCondition: null
productTitleFormat: ''
siteSettings:
  9e4c5b10-0345-4257-a5a8-70987619b1b7: # Fredmansky (de)
    hasUrls: true
    template: shop/products/_product
    uriFormat: 'shop/{slug}-{id}'
skuFormat: ''
variantFieldLayouts:
  a67bde6e-553c-437a-ad57-d0c55318958d:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\commerce\fieldlayoutelements\VariantTitleField
            uid: d18bd3eb-86eb-40ed-8f6c-69e7fc84f31f
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: b1f71cae-6c73-4f94-86fd-fe0b47424764 # Shop: Size
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5f2a41f6-2134-4a26-bdea-583cb989d58e
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: a99d09ae-c4cb-4637-84a1-56662aa4552a # Shop: Gender
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c3498f58-34c4-493a-8a65-ec490d7242dd
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 590acda6-579f-443b-bd12-18f197360039
        userCondition: null
variantTitleFormat: '{product.title}'
