color: null
description: null
fieldLayouts:
  3a5ca891-8226-4d9c-9114-3a054608caad:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-09-10T11:07:32+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 240ec5ae-e1f9-4181-8795-f8b01d335327 # Images
            handle: null
            includeInCards: false
            instructions: null
            label: Bild(er)
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 01748b2a-6264-4ba2-a8e4-73c65abfdfa6
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-09-10T11:07:32+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: e5292c62-f36a-4a67-914e-88eac7fde687 # Newsletter Content Builder - Ãœberschrift - Abstand nach unten
            handle: null
            includeInCards: true
            instructions: null
            label: 'Abstand nach unten'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8027cec0-1dd5-435d-8a29-d869faf269b9
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 72a11815-18d8-4d81-9d35-dcc5a550cc02
        userCondition: null
handle: block_images
hasTitleField: false
icon: null
name: 'Block: Images'
showSlugField: false
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
