color: null
description: null
fieldLayouts:
  8a8553a9-944e-48c8-8323-e1e1cd3db683:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-09-10T11:10:01+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: a68296a9-b5fa-450a-a6c3-2a92ddac6bb3 # Single: Images
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 61a6fe0e-89b8-4c61-9d48-ba4f51e0866f
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 5fb35bc5-9292-47db-88ee-d39dbdb3318d
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-09-10T11:10:01+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: b0f61e15-eec0-4227-b19b-3db8252c752c # Settings: Image Grid
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5413f81e-0b21-43f9-b6d1-d0508ccbcef0
            userCondition: null
            warning: null
            width: 100
        name: Settings
        uid: d7d9d938-2d5e-4dba-b569-a98f16be5a92
        userCondition: null
handle: block_imageGrid
hasTitleField: false
icon: null
name: 'Block: Image Grid'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
