color: null
description: null
fieldLayouts:
  7ee7f25b-e2a0-4d9d-945c-96de24c6afec:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-09-10T11:07:32+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 240ec5ae-e1f9-4181-8795-f8b01d335327 # Images
            handle: null
            includeInCards: false
            instructions: null
            label: Bild(er)
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ebe0d203-54bb-4b5d-82f6-8b637419f4eb
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-09-10T11:07:32+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 284a9b76-c57d-4875-b602-b1d7a28896ae # Newsletter Content Builder - Backstage - Link
            handle: linkInfo
            includeInCards: true
            instructions: null
            label: Link
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e90c3d2f-fc69-4ebb-bef2-f2985697ff54
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 72136ff9-34c6-4f32-a5c2-699d74c6a5cf
        userCondition: null
handle: block_backstage
hasTitleField: false
icon: null
name: 'Block: Backstage'
showSlugField: false
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
