color: null
description: null
fieldLayouts:
  e135ea99-121b-47e6-92c2-7a585e17a6ef:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-09-10T11:12:04+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: f85c7165-6da7-44a9-928c-57095d6f6cfe # Single: Rich Text
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b25d96e0-86a6-472c-874c-70ccd802f45e
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 09d8ae06-1f1a-4957-a9e5-ee30d6aff2e1
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-09-25T14:06:16+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: c92804d7-ed38-4f23-98f4-5876644b09ae # Animate
            handle: null
            includeInCards: false
            instructions: null
            label: 'Animate Text'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d8011c13-9536-4164-b8e0-b462982a9db6
            userCondition: null
            warning: null
            width: 50
        name: Settings
        uid: cd48a30f-f4df-4c04-ab13-a6e513a38e23
        userCondition: null
handle: block_richText
hasTitleField: false
icon: null
name: 'Block: Rich Text'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
