color: null
description: null
fieldLayouts:
  61b8422a-051a-4114-802b-9f1bf4282021:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-09-10T11:09:59+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 84ac7434-30ad-4a0b-af80-92be3627f6b7 # Single: Image Double
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ceef7207-dc4c-4f94-b827-379a1a6d3934
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 43c019d0-d4b5-4a31-9e21-9b3cb1c738c1
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-09-10T11:09:59+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: e911ee58-d44b-4def-84d5-111ec31d3125 # Settings: Image  Double
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4c6d0ce7-b84e-4cbd-88d2-36617c8d8b67
            userCondition: null
            warning: null
            width: 100
        name: Settings
        uid: 07d81dfb-2aff-4cdb-9e86-efcc1d07eaf3
        userCondition: null
handle: block_imageDouble
hasTitleField: false
icon: null
name: 'Block: Image Double'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
