color: null
description: null
fieldLayouts:
  72e8906e-aade-4b98-b595-b7796eec5e63:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\TitleField
            uid: a82c021d-cb85-492d-a540-b5ee655e7fec
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 5bcb2569-dc4a-448a-91db-808aa78cb5a9
        userCondition: null
handle: entry_service
hasTitleField: true
icon: null
name: 'Entry: Service'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
