color: null
description: null
fieldLayouts:
  410eefc6-7cc5-4df1-9601-198d2d5f33c4:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\TitleField
            uid: 3c9704f5-a8e2-4952-8498-0f0c6a63c553
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 6d99e33f-b169-4810-9835-c23b2d3325fa
        userCondition: null
handle: entry_client
hasTitleField: true
icon: null
name: 'Entry: Client'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
