color: null
description: null
fieldLayouts:
  2a5aca91-54a7-493d-80dc-59fc6ecd3d50:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\TitleField
            uid: 576b2bf3-d3eb-414b-adfd-6584266e08ce
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 3deb44c4-aedd-49d6-b26e-8804c7aa9a8d
        userCondition: null
handle: entry_promotionType
hasTitleField: true
icon: null
name: 'Entry: Promotion Type'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
