color: null
description: null
fieldLayouts:
  4ffd35b9-dc5a-458d-8179-9bdaaa5d16d2:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\TitleField
            uid: 65478b10-386d-470a-9773-2f39131b8fe2
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 7be917f2-44ce-48f6-9623-8d7235ccf6de
        userCondition: null
handle: entry_gender
hasTitleField: true
icon: null
name: 'Entry: Gender'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
