color: null
description: null
fieldLayouts:
  fade9438-ea09-454e-ab16-3797e5c09d76:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-09-10T10:49:02+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 73e9ec0e-ad90-456a-bfbc-b7b51c9d2036
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-09-10T10:49:02+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 991258ec-3bf6-445b-a700-ceeeb9d03837 # Headline
            handle: singleEmbedCode
            includeInCards: false
            instructions: "Vimeo embed loop, autoplay, HQ: \r\n`<iframe src=\"https://player.vimeo.com/video/___ID___?autoplay=1&loop=1&autopause=0&quality=1080p&muted=1&background=1&playsinline=1&quality=1080p\" width=\"1920\" height=\"1080\" frameborder=\"0\" allow=\"autoplay; fullscreen\" allowfullscreen></iframe>`"
            label: 'Single: Embed Code'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 18153453-6cf1-4be8-a696-859eb2cac8e6
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 37aff8fe-f4ad-4426-8091-04e7c3756f7a
        userCondition: null
handle: entry_embed
hasTitleField: true
icon: null
name: 'Entry: Embed'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
