color: null
description: null
fieldLayouts:
  33855a13-bca1-46cc-b737-7eef6f70fd6e:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-09-10T10:49:07+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 4ec1a86e-4deb-4a9a-a078-b3667abf1aff
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-09-10T10:49:07+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 3f8d6749-4752-43ac-8c4b-c114bdb261dd # Single: Image
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 65ab9ee7-fe7b-4d4a-9a5e-0e1db7d6877b
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-09-10T10:49:07+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 28ac9431-3120-41a6-a177-85a8f047d82f # Single: Source Url
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4f2920ff-9700-431d-9220-8c13db48361a
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-09-10T10:49:07+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: f85c7165-6da7-44a9-928c-57095d6f6cfe # Single: Rich Text
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9f4824e4-1dc2-4fd2-88d3-155ff962752b
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 48adf64d-2f17-4e0b-a804-5a8322995908
        userCondition: null
handle: entry_gridImageWithText
hasTitleField: true
icon: null
name: 'Entry: Grid Image With Text'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
