color: null
description: null
fieldLayouts:
  9c6843b1-ca20-4c0a-a0ca-54d1438fb034:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-09-10T10:49:29+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: bc90d957-bdf7-49cc-94e4-bc5a0a5c9b83
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-09-10T10:49:29+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: f85c7165-6da7-44a9-928c-57095d6f6cfe # Single: Rich Text
            handle: singleIntroText
            includeInCards: false
            instructions: null
            label: 'Single: Intro Text'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c1767105-7141-44e6-97df-503e7e0f52e6
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: adbd0d83-2675-4d3b-859b-9c928f544c7a
        userCondition: null
handle: entry_textOnly
hasTitleField: true
icon: null
name: 'Entry: Text Only'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
