color: null
description: null
fieldLayouts:
  1a89fda3-97bd-46c6-8921-fc4b84407f36:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-09-10T10:49:06+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 516a4001-3604-4430-9a6d-a5c493c5b770
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-09-10T10:49:06+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 3f8d6749-4752-43ac-8c4b-c114bdb261dd # Single: Image
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 184d86a6-e590-4847-b17d-cee433c9cfb8
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-09-10T10:49:06+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 28ac9431-3120-41a6-a177-85a8f047d82f # Single: Source Url
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 13dd12ad-9cdf-42eb-806f-777b556b5ff8
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 82390083-b8b9-4d02-adb3-48d342c27cfb
        userCondition: null
handle: entry_gridImage
hasTitleField: true
icon: null
name: 'Entry: Grid Image'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
