color: null
description: null
fieldLayouts:
  ea93aeab-c611-49ea-b4a1-ab29a7af2d7b:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-09-19T08:37:50+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 200d500a-5b24-4779-89db-c62a7e2e1c25 # Entry Settings
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e3a72362-0f6a-4a10-876d-e7829446119f
            userCondition: null
            warning: null
            width: 100
        name: Settings
        uid: b18408ac-4bbe-42d5-ab4d-09e80611d85f
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-09-10T10:48:55+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: ed56b94b-9abf-4635-b869-0eb7af8d3c46
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-09-10T10:48:55+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 45592f62-5fb7-4bac-bf2c-9bf95b1d0992 # SEO Settings
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2cd21769-f123-4658-b83f-65fe7ba2e54b
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-09-10T10:48:55+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 07f85313-5d91-415c-9bd3-6cd0acf06af1
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 29c9497f-27ae-486d-83a3-8fc11f276527
            userCondition: null
            warning: null
            width: 100
        name: SEO
        uid: 79338f59-70f0-40d6-9211-0213b6f7990d
        userCondition: null
handle: entry_articles
hasTitleField: true
icon: null
name: 'Entry: Articles'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
