color: null
description: null
fieldLayouts:
  ddd948f0-4ca0-4a74-980b-2d64e0b34c9d:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            fieldUid: 1224b395-dc5d-4f91-b0ac-c229c4b9529b # Grouped: Project Info - Project Title
            handle: null
            includeInCards: true
            instructions: null
            label: 'Project Title'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c7365744-18b7-4cd7-ab56-068feeb64609
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            fieldUid: 4924cecd-f048-4035-b305-ebec6917a2f3 # Single: Rich Text Repeater - Rich Text
            handle: briefing
            includeInCards: false
            instructions: null
            label: Briefing
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0b24bf04-840b-4bb3-98ed-e4ef74d42a5d
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            fieldUid: 4924cecd-f048-4035-b305-ebec6917a2f3 # Single: Rich Text Repeater - Rich Text
            handle: solution
            includeInCards: false
            instructions: null
            label: Solution
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a278e283-242d-4398-bbbd-a90a543621e1
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 4ee98efc-6b3e-4a2c-815d-b26ea6fe407f
        userCondition: null
handle: groupedProjectInfoBlock
hasTitleField: false
icon: null
name: 'Grouped: Project Info Block'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
