color: null
description: null
fieldLayouts:
  50afe9a7-8dae-483a-b620-97505397dd25:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-10-07T12:29:48+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 8011e12b-e953-47c7-92f9-eac402f5bc4e # Settings: Image  Double - Column Ratio
            handle: null
            includeInCards: true
            instructions: null
            label: 'Column Ratio'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3acae619-d574-4b0e-8966-0ad5ccf21de4
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 6e0b4017-75ac-4a4e-8dfa-76d13fb48d83
        userCondition: null
handle: settingsImageDoubleBlock
hasTitleField: false
icon: null
name: 'Settings: Image  Double Block'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
