color: null
description: null
fieldLayouts:
  8ca6e919-0b7b-4e40-a1a8-9daf82a6fb23:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-10-07T07:11:21+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: a536303f-28f8-44ce-a714-7016c49cbefd # Settings: Embed - Embed Position
            handle: null
            includeInCards: false
            instructions: null
            label: 'Embed Position'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e83324fc-19d7-4537-9eb4-dcb4e6ea60c0
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-10-07T07:11:21+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 0a23214e-c6eb-43ae-ba97-6687d0c41bc2 # Settings: Embed - Embed: Width
            handle: null
            includeInCards: false
            instructions: null
            label: 'Embed: Width'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 80c6ef1a-c6bd-4fa2-b6d7-1950c67c4f21
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 4fd1b4a4-ca78-4782-b5df-bec282be8296
        userCondition: null
handle: settingsEmbedBlock
hasTitleField: false
icon: null
name: 'Settings: Embed Block'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
