color: null
description: null
fieldLayouts:
  994b87da-7b90-46c4-830d-78c111a19bd7:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            fieldUid: 51e3766b-5805-45eb-9140-a8bcb61048d5 # Single: Button Group - Button
            handle: null
            includeInCards: true
            instructions: null
            label: Button
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3deb92b3-5cdf-424c-a4d9-72eac506d220
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 5ce649d0-e9b4-4610-bdb9-e880822c0035
        userCondition: null
handle: singleButtonGroupBlock
hasTitleField: false
icon: null
name: 'Single: Button Group Block'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
