headingLevels:
  - 2
  - 3
  - 4
  - 5
  - 6
name: Simple
options:
  link:
    decorators:
      openInNewTab:
        attributes:
          rel: 'noopener noreferrer'
          target: _blank
        label: 'Open in a new tab'
        mode: manual
  list:
    properties:
      styles: false
toolbar:
  - sourceEditing
  - heading
  - bulletedList
  - numberedList
  - link
  - textPartLanguage
  - undo
  - redo
