altTranslationKeyFormat: null
altTranslationMethod: language
fieldLayouts:
  f97b0e3d-f1da-48eb-ba0c-632fa4e69a39:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-09-12T16:12:24+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: 80639037-57fb-4940-883b-fcb5c945799c
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-09-12T16:15:37+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: f6e95218-fc09-4235-a491-471c1c2d3914 # Caption
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 168b8cae-09d5-41b9-ad79-5069ee9de9b5
            userCondition: null
            warning: null
            width: 100
          -
            attribute: alt
            class: null
            cols: null
            dateAdded: '2025-09-12T16:15:37+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            instructions: null
            label: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: true
            required: false
            rows: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AltField
            uid: 0504989a-6257-4ad5-89a9-f9d0d17f6edb
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 17d476e7-8eab-4cfc-9b7e-ecf8aa43c95f
        userCondition: null
fs: shopImages
handle: shopImages
name: 'Shop: Images'
sortOrder: 5
subpath: ''
titleTranslationKeyFormat: null
titleTranslationMethod: none
transformFs: ''
transformSubpath: ''
