altTranslationKeyFormat: null
altTranslationMethod: language
fieldLayouts:
  a6282a9d-2e19-44d2-8776-8eb70035ac58:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-09-12T16:12:23+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: 898ef3e8-e7eb-4682-a3f8-55a245b6c5bb
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-09-12T16:15:06+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: f6e95218-fc09-4235-a491-471c1c2d3914 # Caption
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 28046542-c1d6-4a50-ae45-7c83fdf14eca
            userCondition: null
            warning: null
            width: 100
          -
            attribute: alt
            class: null
            cols: null
            dateAdded: '2025-09-12T16:15:06+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            instructions: null
            label: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: true
            required: false
            rows: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AltField
            uid: de047fa2-084a-4cda-b7a8-c99a779aac9e
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: d2c5e14c-34ba-43cb-94e9-22f5defc5c78
        userCondition: null
fs: siteGraphics
handle: siteGraphics
name: 'Site Graphics'
sortOrder: 0
subpath: ''
titleTranslationKeyFormat: null
titleTranslationMethod: none
transformFs: ''
transformSubpath: ''
