altTranslationKeyFormat: null
altTranslationMethod: none
fieldLayouts:
  f008c697-5ed2-446a-b8d0-45af21c1cdbb:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-10-20T12:05:25+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: 5483c684-ec3a-41cb-9d38-194075e200e0
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-10-20T12:07:09+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: f6e95218-fc09-4235-a491-471c1c2d3914 # Caption
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 05fe560d-d66d-484a-baae-db48e225b008
            userCondition: null
            warning: null
            width: 100
          -
            attribute: alt
            class: null
            cols: null
            dateAdded: '2025-10-20T12:07:09+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            instructions: null
            label: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: true
            required: false
            rows: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AltField
            uid: 4057306f-d453-41a1-aeb7-33e828fd41b9
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 53b27193-4d90-4a8b-b1f0-570d131da973
        userCondition: null
fs: stickers
handle: stickers
name: Stickers
sortOrder: 6
subpath: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: ''
transformSubpath: ''
