columnSuffix: null
handle: embedWidth
instructions: null
name: 'Settings: Embed - Embed: Width'
searchable: true
settings:
  customOptions: false
  options:
    -
      __assoc__:
        -
          - label
          - Full
        -
          - value
          - full
        -
          - default
          - '1'
    -
      __assoc__:
        -
          - label
          - 'Three Quarter'
        -
          - value
          - threeQuarter
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - Half
        -
          - value
          - half
        -
          - default
          - ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Dropdown
