columnSuffix: null
handle: embedPosition
instructions: null
name: 'Settings: Embed - Embed Position'
searchable: true
settings:
  customOptions: false
  options:
    -
      __assoc__:
        -
          - label
          - Left
        -
          - value
          - left
        -
          - default
          - '1'
    -
      __assoc__:
        -
          - label
          - Center
        -
          - value
          - center
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - Right
        -
          - value
          - right
        -
          - default
          - ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Dropdown
