columnSuffix: null
handle: footerTopText
instructions: null
name: 'Footer Top Text'
searchable: true
settings:
  availableTransforms: '*'
  availableVolumes: '*'
  characterLimit: null
  ckeConfig: 25ce68be-0835-4824-a6bd-6dcfa65846c3 # Simple
  createButtonLabel: null
  defaultTransform: null
  expandEntryButtons: false
  fullGraphqlData: true
  parseEmbeds: false
  purifierConfig: null
  purifyHtml: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  showWordCount: true
  sourceEditingGroups:
    - __ADMINS__
  wordLimit: 10
translationKeyFormat: null
translationMethod: none
type: craft\ckeditor\Field
