columnSuffix: null
handle: linkInfo3
instructions: 'Link f√ºr Bild'
name: 'Newsletter Content Builder - Bild(er) - Bild(er) - Link'
searchable: true
settings:
  allowCustomText: false
  allowTarget: false
  defaultText: null
  selectLinkText: ''
  types:
    __assoc__:
      -
        - presseddigital\linkit\models\Email
        -
          __assoc__:
            -
              - enabled
              - ''
            -
              - customLabel
              - ''
            -
              - customPlaceholder
              - ''
      -
        - presseddigital\linkit\models\Phone
        -
          __assoc__:
            -
              - enabled
              - ''
            -
              - customLabel
              - ''
            -
              - customPlaceholder
              - ''
      -
        - presseddigital\linkit\models\Category
        -
          __assoc__:
            -
              - enabled
              - ''
            -
              - customLabel
              - ''
            -
              - sources
              - '*'
            -
              - customSelectionLabel
              - ''
            -
              - userPath
              - ''
      -
        - presseddigital\linkit\models\Asset
        -
          __assoc__:
            -
              - enabled
              - ''
            -
              - customLabel
              - ''
            -
              - sources
              - '*'
            -
              - customSelectionLabel
              - ''
      -
        - presseddigital\linkit\models\User
        -
          __assoc__:
            -
              - enabled
              - ''
            -
              - customLabel
              - ''
            -
              - sources
              - '*'
            -
              - customSelectionLabel
              - ''
            -
              - userPath
              - ''
            -
              - allowHash
              - '1'
            -
              - allowPaths
              - '1'
      -
        - presseddigital\linkit\models\Product
        -
          __assoc__:
            -
              - enabled
              - ''
            -
              - customLabel
              - ''
            -
              - sources
              - '*'
            -
              - customSelectionLabel
              - ''
      -
        - presseddigital\linkit\models\Url
        -
          __assoc__:
            -
              - enabled
              - '1'
            -
              - customLabel
              - ''
            -
              - customPlaceholder
              - ''
            -
              - allowAlias
              - '1'
            -
              - allowMailto
              - '1'
            -
              - allowHash
              - '1'
            -
              - allowPaths
              - '1'
      -
        - presseddigital\linkit\models\Twitter
        -
          __assoc__:
            -
              - enabled
              - ''
            -
              - customLabel
              - ''
            -
              - customPlaceholder
              - ''
      -
        - presseddigital\linkit\models\Facebook
        -
          __assoc__:
            -
              - enabled
              - ''
            -
              - customLabel
              - ''
            -
              - customPlaceholder
              - ''
      -
        - presseddigital\linkit\models\Instagram
        -
          __assoc__:
            -
              - enabled
              - ''
            -
              - customLabel
              - ''
            -
              - customPlaceholder
              - ''
            -
              - customSelectionLabel
              - ''
      -
        - presseddigital\linkit\models\LinkedIn
        -
          __assoc__:
            -
              - enabled
              - ''
            -
              - customLabel
              - ''
            -
              - customPlaceholder
              - ''
            -
              - customSelectionLabel
              - ''
      -
        - presseddigital\linkit\models\Entry
        -
          __assoc__:
            -
              - enabled
              - '1'
            -
              - customLabel
              - ''
            -
              - sources
              - '*'
            -
              - customSelectionLabel
              - ''
translationKeyFormat: null
translationMethod: none
type: presseddigital\linkit\fields\LinkitField
