columnSuffix: null
handle: promotionCategories
instructions: 'Categories used for sales and discount promotions.'
name: 'Promotion Categories'
searchable: true
settings:
  allowSelfRelations: false
  branchLimit: null
  defaultPlacement: end
  maintainHierarchy: true
  maxRelations: null
  minRelations: null
  selectionLabel: 'Add a promotion category'
  showCardsInGrid: false
  showSearchInput: true
  showSiteMenu: true
  source: 'group:10'
  targetSiteId: null
  validateRelatedElements: false
  viewMode: null
translationKeyFormat: null
translationMethod: none
type: craft\fields\Categories
