columnSuffix: null
handle: richTextSimple
instructions: null
name: 'Richtext Simple'
searchable: true
settings:
  availableTransforms: ''
  availableVolumes: ''
  characterLimit: null
  ckeConfig: 25ce68be-0835-4824-a6bd-6dcfa65846c3 # Simple
  createButtonLabel: null
  defaultTransform: null
  expandEntryButtons: false
  fullGraphqlData: false
  parseEmbeds: false
  purifierConfig: null
  purifyHtml: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  showWordCount: false
  sourceEditingGroups: '*'
  wordLimit: null
translationKeyFormat: null
translationMethod: none
type: craft\ckeditor\Field
