columnSuffix: null
handle: settingsAppHeader
instructions: 'Black or white Header. Default is black. '
name: 'Settings: App Header'
searchable: true
settings:
  default: false
  offLabel: null
  onLabel: null
translationKeyFormat: null
translationMethod: none
type: craft\fields\Lightswitch
