columnSuffix: null
handle: singleImageDouble
instructions: null
name: 'Single: Image Double'
searchable: true
settings:
  allowSelfRelations: false
  allowSubfolders: false
  allowUploads: true
  allowedKinds:
    - image
  branchLimit: null
  defaultPlacement: end
  defaultUploadLocationSource: 'volume:ff0b5648-f1d6-418e-ba27-5075ee7ed5ca' # Site Images
  defaultUploadLocationSubpath: null
  maintainHierarchy: false
  maxRelations: 2
  minRelations: null
  previewMode: full
  restrictFiles: true
  restrictLocation: true
  restrictedDefaultUploadSubpath: null
  restrictedLocationSource: 'volume:ff0b5648-f1d6-418e-ba27-5075ee7ed5ca' # Site Images
  restrictedLocationSubpath: null
  selectionLabel: null
  showCardsInGrid: false
  showSearchInput: true
  showSiteMenu: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: true
  sources: '*'
  targetSiteId: 9e4c5b10-0345-4257-a5a8-70987619b1b7 # Fredmansky (de)
  validateRelatedElements: false
  viewMode: list
translationKeyFormat: null
translationMethod: site
type: craft\fields\Assets
