columnSuffix: null
handle: spacingBottom
instructions: null
name: 'Newsletter Content Builder - Ãœberschrift - Abstand nach unten'
searchable: true
settings:
  default: false
  offLabel: null
  onLabel: null
translationKeyFormat: null
translationMethod: none
type: craft\fields\Lightswitch
