columnSuffix: null
handle: style
instructions: null
name: 'Grouped: Project Grid - Doubles - Style'
searchable: true
settings:
  customOptions: false
  options:
    -
      __assoc__:
        -
          - label
          - Landscape
        -
          - value
          - landscape
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - Portrait
        -
          - value
          - portrait
        -
          - default
          - ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Dropdown
