columnSuffix: null
handle: style3
instructions: null
name: 'Settings: ButtonGroup - Style'
searchable: true
settings:
  customOptions: false
  options:
    -
      __assoc__:
        -
          - label
          - Primary
        -
          - value
          - primary
        -
          - default
          - 1
    -
      __assoc__:
        -
          - label
          - Secondary
        -
          - value
          - secondary
        -
          - default
          - ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Dropdown
