columnSuffix: null
handle: textAlignment
instructions: null
name: 'Settings: Image Cover - Text Alignment'
searchable: true
settings:
  customOptions: false
  options:
    -
      __assoc__:
        -
          - label
          - Left
        -
          - value
          - left
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - Center
        -
          - value
          - center
        -
          - default
          - 1
    -
      __assoc__:
        -
          - label
          - Right
        -
          - value
          - right
        -
          - default
          - ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Dropdown
