defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: a1f6f60c-322b-4f9f-be18-92641e5fc621 # Block: Accordion Content
handle: faqs
maxAuthors: 1
name: FAQs
propagationMethod: all
siteSettings:
  9e4c5b10-0345-4257-a5a8-70987619b1b7: # Fredmansky (de)
    enabledByDefault: true
    hasUrls: false
    template: null
    uriFormat: null
structure:
  maxLevels: 2
  uid: f42c4aae-66bf-4f03-818a-2965c1ff7084
type: structure
