defaultPlacement: end
enableVersioning: false
entryTypes:
  -
    uid: 5523e1a6-09ec-41da-8346-f234fc79a17a # Entry: Homepage
handle: homepage
maxAuthors: 1
name: Homepage
previewTargets:
  -
    __assoc__:
      -
        - label
        - Default
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - ''
propagationMethod: all
siteSettings:
  9e4c5b10-0345-4257-a5a8-70987619b1b7: # Fredmansky (de)
    enabledByDefault: true
    hasUrls: true
    template: null
    uriFormat: __home__
type: single
