defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: 07ea13c8-c70a-43de-81d5-2904105386fe # Entry: Team
handle: team
maxAuthors: 1
name: Team
previewTargets:
  -
    __assoc__:
      -
        - label
        - Default
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - ''
propagationMethod: all
siteSettings:
  9e4c5b10-0345-4257-a5a8-70987619b1b7: # Fredmansky (de)
    enabledByDefault: false
    hasUrls: true
    template: null
    uriFormat: 't/{slug}'
type: channel
